#!/usr/bin/env bash
# Install a cli locally

set -TCEeuo pipefail

CLI_NAME=${1-${PROJECT_NAME}}
CLI_HOME=${CLI_HOME:-/opt/${CLI_NAME}}


# Get, check if the parent directory exists
parent_dir=$(dirname "${CLI_HOME}")
if [[ ! -d "${parent_dir}" ]]; then
    echo "Error: Parent directory '${parent_dir}' does not exist or is not a directory."
    exit 1
fi
# Get the owner of the parent directory
# stat gnu first, then stat macos
if ! path_owner=$(stat -c '%U' "${parent_dir}" 2>/dev/null); then
    # Try macOS/BSD stat format if Linux format fails
    if ! path_owner=$(stat -f '%Su' "${parent_dir}" 2>/dev/null); then
      echo "Error: Unable to determine ownership of parent directory '${parent_dir}'."
      exit 1
    fi
fi

# Compare the owner with the current user
current_user=$(whoami)
if [[ "${path_owner}" != "${current_user}" ]]; then
  echo "Parent directory '${parent_dir}' is owned by '${path_owner}', not by current user '${current_user}'. We can't install and move into it"
  exit 1
fi

# Create the package
(cd "$PROJECT_ROOT"; ./mvnw package -DskipTests)
# Download the jdk
(cd "$PROJECT_ROOT"; ./mvnw --no-transfer-progress --batch-mode --file pom.xml -Pjdks -Djdk.name="linux-x64")
# Move the dependencies
(cd "$PROJECT_ROOT"; ./mvnw --no-transfer-progress --batch-mode --quiet --file pom.xml -Pdeps)

# Clean
# mkdir first as the tabulify dir should not exists, other the move command will copy the directory into
mkdir -p "$CLI_HOME" && rm -rf "$CLI_HOME"
ASSEMBLY_DIR=target/jreleaser/assemble/doc-exec-jre/jlink
rm -rf "$ASSEMBLY_DIR"

# Be sure to generate only for the current platform
export JRELEASER_PROJECT_VERSION
JRELEASER_PROJECT_VERSION=$(yq --exit-status '.project.version' "$PROJECT_ROOT/pom.xml")
jreleaser assemble --debug --select-current-platform

# Move the jlink output
# No need to unzip - the dir is still there
ARCHIVE_VERSION_NAME=$JRELEASER_PROJECT_VERSION
# JReleaser change the archive name for snapshot
if [[ "$JRELEASER_PROJECT_VERSION" == *"-SNAPSHOT"* ]]; then
  ARCHIVE_VERSION_NAME=$(yq --exit-status '.project.snapshot.label' jreleaser.yml)
fi
ARCHIVE_NAME=combostrap-${CLI_NAME}-${ARCHIVE_VERSION_NAME}-jre-linux-x64
ASSEMBLY_WORK_DIR=work-linux-x86_64
mv "${ASSEMBLY_DIR}/${ASSEMBLY_WORK_DIR}/${ARCHIVE_NAME}" "${CLI_HOME}"
