#!/usr/bin/env bash


# Be sure to generate only for the current platform
export JRELEASER_PROJECT_VERSION
JRELEASER_PROJECT_VERSION=$(yq --exit-status '.project.version' "$PROJECT_ROOT/pom.xml")

# Jreleaser version
JRELEASER_VERSION=$(yq --exit-status '.project.properties."jreleaser.version"' "$PROJECT_ROOT/pom.xml")

export JRELEASER_GITHUB_TOKEN
JRELEASER_GITHUB_TOKEN="$(pass github/docker-registry)"
# for the docker upload
export JRELEASER_DOCKER_GHCR_IO_PASSWORD="$JRELEASER_GITHUB_TOKEN"
# Same as maven (Default to out)
export JRELEASER_OUTPUT_DIRECTORY=target
# search the .git directory recursively
export JRELEASER_GIT_ROOT_SEARCH=true
# execution directory so that we can execute it from anywhere
export JRELEASER_BASEDIR=$PROJECT_ROOT


# Not needed to be good with agent running locally?
export JRELEASER_GPG_PASSPHRASE="yolo"

# Jdks (used in Jlink package configuration)
export JDK_DOWNLOAD_DIRECTORY # where the jdks are downloaded
JDK_DOWNLOAD_DIRECTORY=$("$PROJECT_ROOT/mvnw" help:evaluate -Dexpression=jdk.download-directory -q -DforceStdout -f "$PROJECT_ROOT/pom.xml")
export JDK_VERSION # jdk version
JDK_VERSION=$("$PROJECT_ROOT/mvnw" help:evaluate -Dexpression=jdk.version -q -DforceStdout -f "$PROJECT_ROOT/pom.xml")
export JDK_DISTRO # jdk distro
JDK_DISTRO=$("$PROJECT_ROOT/mvnw" help:evaluate -Dexpression=jdk.distribution -q -DforceStdout -f "$PROJECT_ROOT/pom.xml")
export DEPENDENCY_OUTPUT_DIRECTORY # jar dependency directory
DEPENDENCY_OUTPUT_DIRECTORY=$("$PROJECT_ROOT/mvnw" help:evaluate -Dexpression=dependency.output-directory -q -DforceStdout -f "$PROJECT_ROOT/pom.xml")

# No env for config file, we add it at the command line so that we can do
# https://jreleaser.org/guide/latest/tools/jreleaser-cli.html#_environment_variables
JRELEASER_CONFIG_FILE="$JRELEASER_BASEDIR/jreleaser.yml"
if [ ! -f "$JRELEASER_CONFIG_FILE" ]; then
  echo "Config file does not exist: $JRELEASER_CONFIG_FILE"
  exit 1
fi

# Extract command
# Why because config file needs to be set after at the cli
COMMAND="$1"
shift # Removes the first argument, leaving the rest in $@

# All relative path are relative to the project root
cd "$PROJECT_ROOT" || exit 1

"$HOME/.sdkman/candidates/jreleaser/${JRELEASER_VERSION}/bin/jreleaser" "$COMMAND" --config-file="$JRELEASER_CONFIG_FILE"  "$@"
