name: Assemble
# Inspiration: https://github.com/jreleaser/helloworld-java-jpackage/blob/main/.github/workflows/reusable-assemble.yml

# Mandatory (manual)
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: false
        type: choice
        default: all
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - all

# Constant for entire workflow
env:
  # The jpackage assembly name
  # It should not change, but it's still a property
  JRELEASER_JPACKAGE_ASSEMBLY_NAME: 'doc-exec-installer'
  JRELEASER_JLINK_ASSEMBLY_NAME: 'doc-exec-standalone'
  JRELEASER_OUT_DIRECTORY: 'target'

jobs:
  assemble:
    name: 'Assemble ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(
          inputs.os == 'all' && '["ubuntu-latest", "windows-latest", "macos-latest"]' ||
          format('["{0}"]', inputs.os)
          ) }}
    runs-on: ${{ matrix.os }}
    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Cache
      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Extract Properties from pom.xml
      # This can take a long time because this is the first invocation of maven
      # so it will download the dependencies
      - name: Properties (Takes time as it downloads maven dependencies)
        id: props
        shell: bash
        run: |
          JDK_VERSION=$(./mvnw help:evaluate -Dexpression=jdk.version -q -DforceStdout)
          echo "jdk_version=$JDK_VERSION" >> $GITHUB_OUTPUT
          JDK_DISTRO=$(./mvnw help:evaluate -Dexpression=jdk.distribution -q -DforceStdout)
          echo "jdk_distro=$JDK_DISTRO" >> $GITHUB_OUTPUT
          PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "project_version=$PROJECT_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.props.outputs.jdk_version }}
          distribution: ${{ steps.props.outputs.jdk_distro }}
          cache: maven

      # Run the jdks profile default goal with maven wrapper
      # Why temp? temp is the root location of the jdks
      - name: Setup JDKs
        # The shell is bash on Linux and Powershell in Windows
        # Setting the shell to bash does not work on Windows
        # ---
        # We quote -Djava.io.tmpdir because `-Djava.io.tmpdir=D:\a\_temp`
        # in Powershell is being parsed as a PowerShell parameter -<parameter_name>:<parameter_value>
        # rather than being passed to Maven.
        run: ./mvnw "-Djava.io.tmpdir=${{ runner.temp }}" --no-transfer-progress --batch-mode --file pom.xml -Pjdks

      # Run the deps profile default goal with maven wrapper
      # Jlink packaging needs them
      - name: Copy dependencies
        run: ./mvnw --no-transfer-progress --batch-mode --quiet --file pom.xml -Pdeps

      # Test only on Linux
      # On Windows, we get when calling bash in a test: `Windows Subsystem for Linux has no installed distributions`
      - name: Test
        if: runner.os != 'Windows'
        run: ./mvnw --no-transfer-progress --batch-mode --file pom.xml test

      # Build jar
      - name: Build
        run: ./mvnw --no-transfer-progress --batch-mode --file pom.xml -DskipTests package

      # Wix v3 is needed by Jpackage
      - name: Install WiX v3
        if: runner.os == 'Windows'
        # silent = no GUI windows, progress bars, or installer dialogs
        # force = to avoid the error: `Found an existing package already installed`
        # https://learn.microsoft.com/en-us/windows/package-manager/winget/install
        run: winget install -e --id WiXToolset.WiXToolset -v 3.14.1.8722 --silent --accept-source-agreements --accept-package-agreements --force

      # Jlink and Jpackage assembly
      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble --select-current-platform
          setup-java: false
        env:
          JRELEASER_PROJECT_VERSION: ${{ steps.props.outputs.project_version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_OUTPUT_DIRECTORY: ${{ env.JRELEASER_OUT_DIRECTORY }}
          TMP: ${{ runner.temp }} # temp is the root location of the jdks

      # Upload log
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-assemble-${{ runner.os }}-${{ runner.arch }}
          path: |
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/trace.log
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/output.properties

      # Upload Jpackage native package
      # Jlink artifact is not in this upload because we download them into a different directory
      # ie JReleaser expects the Jlink and Native Package in different directory
      - name: Upload Jpackage Native Package
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: jpackage-${{ runner.os }}-${{ runner.arch }}
          path: |
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.pkg
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.msi
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.deb
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JPACKAGE_ASSEMBLY_NAME}}/jpackage/*.rpm

      # Upload Jlink native package
      - name: Upload Jlink Archive
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: jlink-${{ runner.os }}-${{ runner.arch }}
          path: |
            ${{env.JRELEASER_OUT_DIRECTORY}}/jreleaser/assemble/${{env.JRELEASER_JLINK_ASSEMBLY_NAME}}/jlink/*.zip